### ISSUE TITLE
Specific directives for the same user-agent in different groups are ignored

### ISSUE THREAD

**Issue by sanderheilbron** [trachelas/robotto#75]
When the same user-agent (start of group) is used for several groups, only the directives (disallow, allow) of the last group are followed. This does not match to how Googlebot handles robots.txt files.

Example:

User-Agent: *
Disallow: /folder-1/*

User-Agent: *
Disallow: /folder-2/*

User-Agent: *
Disallow: /page-a

User-Agent: *
Disallow: /page-b

Robotto adds the disallow directive of /page-b to the disallow array, but ignores the preceding directives. Following to how Googlebot handles robots.txt files, all disallow directives should be added to the array of the user-agent (*) object.

**Comment by lucasfcosta** [comment]
@sanderheilbron thanks for your issue and for the detailed description!
I'll take a look at it!

**Comment by lucasfcosta** [comment]
Fixed on #76
