### ISSUE TITLE
(node:23420) Warning: Possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by coderingo** [trachelas/robotto#80]
Hi Again :)

When crawling a link for robots.txt with a redirect loop,  request.js throws the following error:

`(node:23420) Warning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit`

It will be good to have a limit on the maximum Redirects. Google supports upto 4 redirects for robots.txt 

If we can update the robotsUrl to an object of options then it can solve the problem. Alternatively, we can specify in the documentations that robotto.fetch method can take an object as first arguments where options for request.js can be submitted.

I submitted a partial pull request (without re-writing tests) but then I closed it thinking that it should be best left to the library creator to go either ways. Summary of the issue is to prevent possible memory leaks in production and inform the users of the possible issue and its solution. 

Kind Regards

**Comment by coderingo** [comment]
I forgot, robotto.fetch cannot take an object as it re-evaluates the urlIP argument using getRobotsUrl(urlP).  I think an edit to the fetch() method will be the only way to prevent this issue.

**Comment by vieiralucas** [comment]
Hello @coderingo 
Thanks for your issue

I see 3 options to fix this

1. Add a `maxRedirects` parameter to `fetch`
2. Hardcode a `maxRedirects` ourselves [RFC 1945](https://www.ietf.org/rfc/rfc1945.txt) specifies `5` as the maximum.
> 9.3  Redirection 3xx
>
>   This class of status code indicates that further action needs to be
>   taken by the user agent in order to fulfill the request. The action
>   required may be carried out by the user agent without interaction
>   with the user if and only if the method used in the subsequent
>   request is GET or HEAD. **A user agent should never automatically
>   redirect a request more than 5 times**, since such redirections usually
>   indicate an infinite loop.

3. Do both, i.e. add a parameter that defaults to 5

@coderingo, @lucasfcosta What do you think?

I prefer number 2

**Comment by coderingo** [comment]
Hi @vieiralucas 

I agree with you, Option 2 is most suitable.  Most users will prefer going with the standards defined. I vote for hardcoding maxRedirects. 

Looking forward to the update :) 

Sincerely,

**Comment by lucasfcosta** [comment]
Hi everyone, thanks for sharing your thoughts.
Option 2 is the most suitable IMO too.
Let's stick with the standards.
